# Generated by Django 6.1.1 on 2026-09-15 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_country_user_position_user_social_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('EMAIL_VERIFY', 'Email verification'), ('PASSWORD_RESET', 'Password reset')], max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otp_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'is_used'], name='otp_codes_user_id_c67bdc_idx')],
            },
        ),
    ]
