# Generated by Django 6.1.1 on 2026-09-09 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('HIGHEST_RATING', 'Highest Rating'), ('MOST_GOALS', 'Most Goals'), ('MOST_WINS', 'Most Wins'), ('LONGEST_WIN_STREAK', 'Longest Winning Streak'), ('MOST_GOALS_IN_MATCH', 'Most Goals in One Match'), ('MOST_TOURNAMENT_WINS', 'Most Tournament Wins'), ('BEST_WIN_RATE', 'Best Win Rate'), ('BIGGEST_WINNING_MARGIN', 'Biggest Winning Margin'), ('MOST_CLEAN_SHEETS', 'Most Clean Sheets')], max_length=25)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='leagues.league')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_set', to='matches.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'league_records',
                'ordering': ['-value'],
                'unique_together': {('league', 'record_type', 'is_current')},
            },
        ),
    ]
