# Generated by Django 6.1.1 on 2026-09-12 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
        ('matches', '0004_match_venue'),
        ('records', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaguerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='leaguerecord',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league_records', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='leaguerecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='leaguerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('league', 'record_type'), name='unique_current_record_per_type'),
        ),
    ]
