# Generated by Django 6.1.1 on 2026-09-09 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('matches', '0001_initial'),
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('TOURNAMENT_INVITATION', 'Tournament Invitation'), ('TOURNAMENT_REGISTRATION', 'Tournament Registration'), ('FIXTURE_ASSIGNED', 'Fixture Assigned'), ('MATCH_REMINDER', 'Match Reminder'), ('EVIDENCE_UPLOADED', 'Evidence Uploaded'), ('AI_VERIFICATION_COMPLETE', 'AI Verification Complete'), ('ADMIN_REVIEW_REQUIRED', 'Admin Review Required'), ('MATCH_VERIFIED', 'Match Verified'), ('MATCH_REJECTED', 'Match Rejected'), ('DISPUTE_UPDATE', 'Dispute Update'), ('TOURNAMENT_STARTED', 'Tournament Started'), ('ROUND_COMPLETED', 'Round Completed'), ('TOURNAMENT_COMPLETED', 'Tournament Completed'), ('AWARD_RECEIVED', 'Award Received'), ('LEAGUE_INVITATION', 'League Invitation')], max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='leagues.league')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='matches.match')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_invitations', models.BooleanField(default=True)),
                ('match_results', models.BooleanField(default=True)),
                ('dispute_updates', models.BooleanField(default=True)),
                ('awards', models.BooleanField(default=True)),
                ('league_updates', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=False)),
                ('email_enabled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
    ]
