# Generated by Django 6.1.1 on 2026-09-09 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidence', '0001_initial'),
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AI_PROCESSING', 'AI Processing'), ('AI_VERIFIED', 'AI Verified'), ('ADMIN_REVIEW', 'Admin Review'), ('DISPUTED', 'Disputed'), ('REJECTED', 'Rejected'), ('VERIFIED', 'Verified')], default='PENDING', max_length=20)),
                ('ai_extracted_data', models.JSONField(blank=True, default=dict)),
                ('ai_confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('ai_provider', models.CharField(default='placeholder', max_length=100)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tasks', to='evidence.evidencestorage')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_task', to='matches.match')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.CharField(blank=True, max_length=500, null=True)),
                ('confidence', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('source_region', models.CharField(blank=True, default='', max_length=200)),
                ('is_reliable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verification_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_results', to='verification.verificationtask')),
            ],
            options={
                'db_table': 'extraction_results',
                'ordering': ['field_name'],
            },
        ),
    ]
