# Generated by Django 6.1.1 on 2026-09-09 13:07

import django.db.models.deletion
import tournaments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('seasons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('tournament_code', models.CharField(default=tournaments.models.generate_tournament_code, max_length=10, unique=True)),
                ('format', models.CharField(choices=[('LEAGUE', 'League'), ('KNOCKOUT', 'Knockout'), ('GROUP_KNOCKOUT', 'Group + Knockout'), ('CUSTOM', 'Custom')], default='KNOCKOUT', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REGISTRATION_OPEN', 'Registration Open'), ('REGISTRATION_CLOSED', 'Registration Closed'), ('SEEDING', 'Seeding'), ('FIXTURES_GENERATING', 'Fixtures Generating'), ('READY', 'Ready'), ('IN_PROGRESS', 'In Progress'), ('SUSPENDED', 'Suspended'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=25)),
                ('max_participants', models.PositiveIntegerField(default=16)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tournaments', to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='leagues.league')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='seasons.season')),
            ],
            options={
                'db_table': 'tournaments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('group_number', models.PositiveIntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'tournament_groups',
                'ordering': ['group_number'],
                'unique_together': {('tournament', 'group_number')},
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('CONFIRMED', 'Confirmed'), ('ACTIVE', 'Active'), ('ELIMINATED', 'Eliminated'), ('WITHDRAWN', 'Withdrawn')], default='REGISTERED', max_length=20)),
                ('seed_number', models.PositiveIntegerField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tournament_participants',
                'ordering': ['seed_number', 'registered_at'],
                'unique_together': {('tournament', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TournamentStateTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=25)),
                ('to_status', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_transitions', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'tournament_state_transitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tournaments.tournamentgroup')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='tournaments.tournamentparticipant')),
            ],
            options={
                'db_table': 'tournament_group_members',
                'ordering': ['position'],
                'unique_together': {('group', 'participant')},
            },
        ),
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('round_number', models.PositiveIntegerField()),
                ('round_type', models.CharField(default='KNOCKOUT', max_length=50)),
                ('is_current', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournaments.tournament')),
            ],
            options={
                'db_table': 'tournament_rounds',
                'ordering': ['round_number'],
                'unique_together': {('tournament', 'round_number')},
            },
        ),
    ]
