# Generated by Django 6.1.1 on 2026-09-12 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentparticipant',
            unique_together={('tournament', 'user')},
        ),
        migrations.AddField(
            model_name='tournament',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/banners/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='game',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_team_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/logos/'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='min_participants',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rules',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participations', to='teams.team'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('LEAGUE', 'League'), ('ROUND_ROBIN', 'Round Robin'), ('GROUP_STAGE', 'Group Stage'), ('KNOCKOUT', 'Knockout'), ('GROUP_KNOCKOUT', 'Group + Knockout'), ('CUSTOM', 'Custom')], default='KNOCKOUT', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentparticipant',
            unique_together={('tournament', 'team'), ('tournament', 'user')},
        ),
    ]
