# Generated by Django 6.1.1 on 2026-09-10 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('min_rating', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_rating', models.DecimalField(decimal_places=2, default=99999, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(default='#e94560', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='leagues.league')),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['min_rating'],
                'unique_together': {('league', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='PlayerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='categories.category')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'player_categories',
                'ordering': ['-is_primary', 'assigned_at'],
                'unique_together': {('player', 'category')},
            },
        ),
    ]
