# Generated by Django 6.1.1 on 2026-09-09 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('AWAITING_RESULT', 'Awaiting Result'), ('EVIDENCE_SUBMITTED', 'Evidence Submitted'), ('AI_PROCESSING', 'AI Processing'), ('ADMIN_REVIEW', 'Admin Review'), ('DISPUTED', 'Disputed'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=25)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_idempotent_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('away_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to=settings.AUTH_USER_MODEL)),
                ('home_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='leagues.league')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournaments.tournamentround')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_reference', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('source_type', models.CharField(choices=[('SCREENSHOT', 'Screenshot'), ('VIDEO', 'Video'), ('MANUAL', 'Manual')], default='SCREENSHOT', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='matches.match')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_evidences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'match_evidences',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchStateTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=25)),
                ('to_status', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_transitions', to='matches.match')),
            ],
            options={
                'db_table': 'match_state_transitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_possession', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('away_possession', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('home_shots', models.PositiveIntegerField(blank=True, null=True)),
                ('away_shots', models.PositiveIntegerField(blank=True, null=True)),
                ('home_shots_on_target', models.PositiveIntegerField(blank=True, null=True)),
                ('away_shots_on_target', models.PositiveIntegerField(blank=True, null=True)),
                ('home_pass_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('away_pass_accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('home_tackles', models.PositiveIntegerField(blank=True, null=True)),
                ('away_tackles', models.PositiveIntegerField(blank=True, null=True)),
                ('home_corners', models.PositiveIntegerField(blank=True, null=True)),
                ('away_corners', models.PositiveIntegerField(blank=True, null=True)),
                ('home_fouls', models.PositiveIntegerField(blank=True, null=True)),
                ('away_fouls', models.PositiveIntegerField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_raw_output', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='matches.match')),
            ],
            options={
                'db_table': 'match_statistics',
            },
        ),
        migrations.CreateModel(
            name='MatchVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AI_PROCESSING', 'AI Processing'), ('AI_VERIFIED', 'AI Verified'), ('ADMIN_REVIEW', 'Admin Review'), ('DISPUTED', 'Disputed'), ('REJECTED', 'Rejected'), ('VERIFIED', 'Verified')], default='PENDING', max_length=20)),
                ('ai_extracted_data', models.JSONField(blank=True, default=dict)),
                ('ai_confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='matches.match')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'match_verifications',
            },
        ),
    ]
