# Generated by Django 6.1.1 on 2026-09-10 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('GOAL', 'Goal'), ('OWN_GOAL', 'Own Goal'), ('YELLOW_CARD', 'Yellow Card'), ('RED_CARD', 'Red Card'), ('ASSIST', 'Assist'), ('SAVE', 'Save'), ('PENALTY_SCORED', 'Penalty Scored'), ('PENALTY_MISSED', 'Penalty Missed')], max_length=20)),
                ('minute', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assisted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assists', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'match_events',
                'ordering': ['minute', 'created_at'],
            },
        ),
    ]
