# Generated by Django 6.1.1 on 2026-09-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_away_team_match_home_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
