# Generated by Django 6.1.1 on 2026-09-09 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerLeagueRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, default=1000.0, max_digits=7)),
                ('peak_rating', models.DecimalField(decimal_places=2, default=1000.0, max_digits=7)),
                ('matches_rated', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_ratings', to='leagues.league')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'player_league_ratings',
                'ordering': ['-rating'],
                'unique_together': {('league', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RatingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_rating', models.DecimalField(decimal_places=2, max_digits=7)),
                ('new_rating', models.DecimalField(decimal_places=2, max_digits=7)),
                ('rating_change', models.DecimalField(decimal_places=2, max_digits=7)),
                ('opponent_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('result', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_history', to='leagues.league')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_changes', to='matches.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rating_history',
                'ordering': ['-created_at'],
                'unique_together': {('league', 'user', 'match')},
            },
        ),
    ]
