# Generated by Django 6.1.1 on 2026-09-09 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_reference', models.CharField(max_length=500)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_type', models.CharField(max_length=50)),
                ('checksum', models.CharField(max_length=64)),
                ('is_valid', models.BooleanField(default=False)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_evidence', to='matches.match')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evidence_storage',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
