# Generated by Django 6.1.1 on 2026-09-09 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('seasons', '0001_initial'),
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_type', models.CharField(choices=[('PLAYER_OF_SEASON', 'Player of the Season'), ('GOLDEN_BOOT', 'Golden Boot'), ('GOLDEN_BALL', 'Golden Ball'), ('TOURNAMENT_MVP', 'Tournament MVP'), ('BEST_DEFENDER', 'Best Defender'), ('BEST_PERFORMER', 'Best Performer'), ('PLAYER_OF_MONTH', 'Player of the Month'), ('FAIR_PLAY', 'Fair Play Award'), ('LEAGUE_CHAMPION', 'League Champion'), ('TOURNAMENT_CHAMPION', 'Tournament Champion'), ('RUNNER_UP', 'Runner-up'), ('CUSTOM', 'Custom Award')], max_length=25)),
                ('custom_name', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(choices=[('AUTO', 'Auto Calculated'), ('MANUAL', 'Manually Assigned'), ('OVERRIDE', 'Manual Override')], default='AUTO', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards_given', to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='leagues.league')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='seasons.season')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='tournaments.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'awards',
                'ordering': ['-awarded_at'],
                'unique_together': {('league', 'season', 'tournament', 'award_type', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AwardAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='awards.award')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award_changes', to=settings.AUTH_USER_MODEL)),
                ('new_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_awards', to=settings.AUTH_USER_MODEL)),
                ('previous_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'award_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
