# Generated by Django 6.1.1 on 2026-09-12 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('short_name', models.CharField(blank=True, default='', max_length=20)),
                ('slug', models.SlugField(max_length=140)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='teams/banners/')),
                ('description', models.TextField(blank=True, default='')),
                ('game', models.CharField(blank=True, default='', max_length=100)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_teams', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teams', to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='leagues.league')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CAPTAIN', 'Captain'), ('PLAYER', 'Player'), ('SUBSTITUTE', 'Substitute'), ('COACH', 'Coach')], default='PLAYER', max_length=20)),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team_members',
                'ordering': ['role', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('goals_scored', models.PositiveIntegerField(default=0)),
                ('goals_conceded', models.PositiveIntegerField(default=0)),
                ('clean_sheets', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('form', models.JSONField(blank=True, default=list)),
                ('current_win_streak', models.PositiveIntegerField(default=0)),
                ('best_win_streak', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='teams.team')),
            ],
            options={
                'verbose_name_plural': 'team statistics',
                'db_table': 'team_statistics',
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['league', 'is_active'], name='teams_league__3267e4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('league', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'user')},
        ),
    ]
