# Generated by Django 6.1.1 on 2026-09-09 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('seasons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=0)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('goals_for', models.PositiveIntegerField(default=0)),
                ('goals_against', models.PositiveIntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='leagues.league')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standings', to='seasons.season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_standings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'league_standings',
                'ordering': ['-points', '-goal_difference', '-goals_for'],
                'unique_together': {('league', 'season', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PlayerLeagueStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('goals_scored', models.PositiveIntegerField(default=0)),
                ('goals_conceded', models.PositiveIntegerField(default=0)),
                ('clean_sheets', models.PositiveIntegerField(default=0)),
                ('win_streak', models.PositiveIntegerField(default=0)),
                ('current_win_streak', models.PositiveIntegerField(default=0)),
                ('best_win_streak', models.PositiveIntegerField(default=0)),
                ('longest_unbeaten', models.PositiveIntegerField(default=0)),
                ('total_goals_in_match', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_statistics', to='leagues.league')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_statistics', to='seasons.season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'player_league_statistics',
                'ordering': ['-wins', '-goals_scored'],
                'unique_together': {('league', 'user', 'season')},
            },
        ),
    ]
